name: Deploy to Dev environment
on:
  push:
    branches:
      - test
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/terraform-ci.yml
    with:
      environment: dev
      region: eu-central-1
      working-directory: infrastructure/environments/application/eu-central-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.DEV_AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.DEV_AWS_SECRET_ACCESS_KEY}}